### ISSUE TITLE
Composite recipes

### ISSUE THREAD

**Issue by majori** [futurice/jalapeno#52]
Instead of applying multiple recipes to projects multiple times, we could define an "umbrella" recipe, which applies multiple recipes in a single recipe execution. The feature would work similarly as in [Helm](https://helm.sh/docs/chart_best_practices/dependencies/)

**Comment by majori** [comment]
Alternative method would be to have a manifest file, which defines what recipes should be pulled and executed. For example `jalapeno execute --manifest path/to/file`

**Comment by ilkka** [comment]
So, if we go for umbrella recipes, what that would mean in practice is, recipes can have dependencies, which is fine in my book, and then I guess we need some sort of DAG solver to work out the actual execution order from a graph of deps. The dependencies themselves would then probably most often be OCI URLs? We can pass a single set of repo credentials but for multiple authenticated OCI repositories, I guess it'd then be up to the user to `docker login` to all of them?

**Comment by majori** [comment]
I think we should handle it like Helm does, so copy of the dependencies are always packaged to the recipe when pushed to a registry. So then there would be no need for multiple credentials when the user wants to use the recipe

**Comment by ilkka** [comment]
Ohhh right right, I actually didn't know Helm does that.

So: a recipe can have dependencies, so it'd be something like

```yaml
apiVersion: v1
name: with-dependencies
version: v1.0.0
description: This recipe has dependencies
dependencies:
  # like this or with a plain OCI URL?
  - name: a-dependency
    version: "1.2.3"
    repository: oci://example.com/my-repo/
```

and then we'd have the command `jalapeno dependency build` that would populate a "dependencies" directory?

For that, we would load the "umbrella recipe", then load the first level dependencies and start building a graph. Then if there's a loop, that's an error and we stop, or if we hit two different versions of the same dependency, also an error and we stop.

As for execution, start with the root recipe and go depth-first, that should work, then our normal conflict resolution should deal with any of those.

Does that sound workable? The manifest approach would definitely be a lot simpler, but also a lot more limited.
